### ISSUE TITLE
`pressedIconName` / `pressedIcon` property of toggleButton

### ISSUE THREAD

**Issue by annarieger** [terrestris/react-geo#1717]
if one of `iconName` or `icon` is set as prop on ToggleButton, one of`pressedIconName`or `pressedIcon` must be set as well. Otherwise the button turns invisible (`ant-btn:empty` class will be added) after the button was toggled.

Example:
```
<ToggleButton
  iconName="frown-o"
  // pressedIconName="smile-o" --> without this prop the button gets broken on toggle
  onToggle={()=>{}}
/>
```

**Comment by Unraveler** [comment]
Hi @annarieger ,
You are correct, `ant` is setting this to hidden if no text or icon are given. It makes sense in general to provide both a pressed icon and a default icon, or maybe a text, making the button not always empty. But sometimes our code logic may required otherwise. For this reason, I am setting a new class in the react-geo-togglebutton style

```
// overrides the ant-btn:empty style, that is setting the button to hidden if no text or icon are given
  &:empty {
    visibility: visible;
  }
```
This will fix the issue
