### ISSUE TITLE
Unable to use this component in a Nextjs app

### ISSUE THREAD

**Issue by sturlath** [terrestris/react-geo#1799]
I get the following error when trying to use the component in a Nextjs app

`error - ./node_modules/@ag-grid-community/core/dist/styles/ag-grid.css
Global CSS cannot be imported from within node_modules.`

and a link to [a possible fix](https://github.com/vercel/next.js/blob/master/errors/css-npm.md) on this end.

Is this something I can do to overcome this?

**Comment by dnlkoch** [comment]
Hi @sturlath, we don't have any experience of using `react-geo` in a `Next.js` app (yet), but according to [this issue](https://github.com/vercel/next.js/issues/12079) importing css files from `node_modules` should be available since version `next@^9.5.4-canary.10`. Did you check that out? There are several other hints mentioned in the thread you might want to check as well.
