### ISSUE TITLE
Use ag-Grid instead of Ant table

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#432]
As we discovered a lot of limitiations regarding the antd table component during development we should think about changing the underlying grid component to ag-Grid.

**Comment by KaiVolland** [comment]
Missing Features:
- Resizable Columns
- Draggable Columns
- Sort on HeaderClick

**Comment by dnlkoch** [comment]
Yes, for more complex tables we should definitely consider using the `ag-grid` component, but in my opinion we shouldn't replace all `antd` tables blindly without having any need of the more advanced features.

**Comment by hwbllmnn** [comment]
It's implemented in #588 . One thing that's missing: the order of the columns is currently not configurable, since the `columnDefs` prop is an object. In ag-grid the column definitions are an array, so we'll have to create the proper order ourselves when we process the config.

Alternatively we can change the `columnDefs` prop to be an array, breaking backwards compatibility.

**Comment by hwbllmnn** [comment]
I just added support for an `index` property for column definitions to #588 .

**Comment by dnlkoch** [comment]
There are some commented tests in the current implementation. We should fix the issue of the missing `grid` state and reactivate them.

**Comment by marcjansen** [comment]
What is the summarized state here?

**Comment by dnlkoch** [comment]
Feature grid based on `ag-grid` is available and all issues listed here (missing index, disabled tests) are resolved.
