### ISSUE TITLE
Upgrade to ol v5

### ISSUE THREAD

**Issue by KaiVolland** [terrestris/react-geo#515]
As @ahocevar suggested in his FOSSGIS talk.

We should prepare the upgrade of ol. If i'm right the main change will be the import pathes. As the classes are now written in UpperCase.

Maybe this will be an API-breaking change…

**Comment by marcjansen** [comment]
It'll be a bit more...

**Comment by annarieger** [comment]
[This branch](https://github.com/annarieger/react-geo/tree/ol5-upgrade/) contains first preparation steps to be able to use `react-geo` classes  with `ol5` in the future. All examples as well as tests of `react-geo` package are adapted as well.

Mostly important changes:
* `ol` modules imports are in camelcase now (e.g. `ol/Map` instead of `ol/map`)
* for some classes named imports for certain function will be used now

The branch is currently based on [v5.0.0-beta.10 release](https://github.com/openlayers/openlayers/tree/beta) of `ol` and considers all for our project significant upgrade notes from [here](https://github.com/openlayers/openlayers/blob/b1c741ca4a5b7a1d623adff4f2cf4b030e8d52d7/changelog/upgrade-notes.md) and [here](https://github.com/openlayers/openlayers/wiki/OpenLayers-v5.x).

It can be tested locally after `ol` dependency is set to `v5.0.0-beta.10` with the following command:
```
npm i ol@v5.0.0-beta.10
```

**Comment by annarieger** [comment]
Here we go --> https://github.com/terrestris/react-geo/pull/606 :innocent:

**Comment by marcjansen** [comment]
Constantly updated PR is #631

**Comment by annarieger** [comment]
#606 is closed in favor of #631.
